# Практическая работа №3

In [1]:
my_txt = 'cdsg csdgrwef sdSHJAA? DASFA /DFSDFA \n asdFA'
l = my_txt.split(' ')
f = []
for i in l:
    f.append(len(i))

print(f)

[4, 8, 8, 5, 7, 1, 5]


# Практическая работа №4
Задание А

In [13]:
CLASSFIC_ROAD = {'Здания повышенной этажности' : [30],
              ' I категория многоэтажных зданий' : [50],
              'II категория' : [75],
              'III категория' : [100]
}

text = "Здание КБ47 имеет высоту 50 метра."

def analysing_txt(text, dictionary):
    num = []
    num = [int(x) for x in text.split() if x.isdigit()] 
    for i in dictionary:
        if num[0] < dictionary.setdefault(i)[0] :
            return(i)
        elif num[0] >= 100:
            return ('высотные здания')
        
print(analysing_txt(text, CLASSFIC_ROAD))

II категория


Задание B

In [15]:
import collections
import json

id_pick = []
with open ("..//data.json", "r") as file:
    data = json.load(file)
    events = data.setdefault("events_data")
    c = collections.Counter()
    for i in range(0,len(events)):
        if events[i]['category'] == 'page' or events[i]['category'] =='report':
            id_pick.append(events[i]['client_id'])
    for g in id_pick:
            c[g]+=1
    print(len(c))

51


# Практическая работа №5

In [68]:
import numpy as np #Библиотека NumPy. Импорт библиотеки
#Создание массива. Функции array() и values().

F = np.random.randint(0,101,(5,4))
print(F)

maxim = np.max(F)
print(maxim)
G = F/maxim
var = np.var(G)
print(round(var,2), 'стандартная функция')
mid = np.mean(G)
print(round(mid,2), 'стандартная функция')
summ = 0
for i in range(len(G)):
    for g in range(len(G[i])):
        summ+=G[i][g]
mean = summ/(len(G)*len(G[0]))
print(round(mean,2), 'собственная программа')
var_p = 0
for i in range(len(G)):
    for g in range(len(G[i])):
        var_p+=(G[i][g] - mean)**2
print(round(var_p/(len(G)*len(G[0])),2), 'собственная программа')

[[42 55 77 39]
 [99 11 61  1]
 [24 85 26 61]
 [29  0 99 82]
 [31 64 13 60]]
99
0.09 стандартная функция
0.48 стандартная функция
0.48 собственная программа
0.09 собственная программа
