# Практическая работа №5

In [52]:
import numpy as np #Библиотека NumPy. Импорт библиотеки
#Создание массива. Функции array() и values().

F = np.random.randint(0,101,(4,4))
print(F)
G = np.transpose(F)

b = [sum(G[x]) for x in range(len(G))]
print(b)
index = b.index(max(b))

mid = np.median(G[index])
print(mid, 'стандартная функция')



srt = np.sort(G[index])
coord = len(srt)//2
if len(G[index])%2==0:
    mean = (srt[coord]+srt[coord-1])/2
    print(mean, 'собственная функция')
else:
    print(srt[coord], 'собственная функция')

[[39 46 21 63]
 [10 76 82 67]
 [61 15 10 44]
 [80 88 29 48]]
[190, 225, 142, 222]
61.0 стандартная функция
61.0 собственная функция


# Практическая работа №6

In [21]:
import numpy as np
import pandas as pd

df = pd.read_csv('../football.csv')

A = min(df['Aggression'])
B = max(df['Aggression'])
C = df.groupby('Aggression').agg({'ShotPower': 'mean'})
C['Aggression']=C.index
G = C.loc[C['Aggression'] == A]
I = C.loc[C['Aggression'] == B]

c =map(lambda x,y:x/y,I['Aggression'],G['Aggression'])
list(c)

[8.636363636363637]

In [6]:
df['Composure'].describe()

count    12897.000000
mean        55.942932
std         11.280631
min         12.000000
25%         49.000000
50%         56.000000
75%         63.000000
max         96.000000
Name: Composure, dtype: float64

# Практическая работа №7

### задание А

In [56]:
import numpy as np
import pandas as pd

df = pd.read_csv('../StudentsPerformance.csv')

g = list(map(lambda x,y: x == 'female' and y == "master's degree",
             df['gender'], df['parental level of education']))
c = filter(lambda x: x == True, g)
print(len(list(c)), 'девочек, у которых родители имеют степень баклавра')

36 девочек, у которых родители имеют степень баклавра


### задание B

In [84]:
def cat(row): 
    if row[2].find('degree')!=-1:
        return 'высшая категория'
    elif row[2].find('school')!=-1 and row[2].find('some')!=-1:
        return 'средняя категория'
    elif row[2].find('school')!=-1 and row[2].find('some')==-1:
        return 'выше среднего'
    elif row[2].find('college')!=-1:
        return 'низшая'
    
    
cat_ed = map(lambda x: cat(list(df.iloc[x])), range(len(df['parental level of education'])))

df['education_cat'] = list(cat_ed)
df

gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard   
1    female        group C                some college      standard   
2    female        group B             master's degree      standard   
3      male        group A          associate's degree  free/reduced   
4      male        group C                some college      standard   
..      ...            ...                         ...           ...   
995  female        group E             master's degree      standard   
996    male        group C                 high school  free/reduced   
997  female        group C                 high school  free/reduced   
998  female        group D                some college      standard   
999  female        group D                some college  free/reduced   

    test preparation course  math score  reading score  writing score  \
0                      none          72             72             74   
1                 completed          69             90             88   
2                      none          90             95             93   
3                      none          47             57             44   
4                      none          76             78             75   
..                      ...         ...            ...            ...   
995               completed          88             99             95   
996                    none          62             55             55   
997               completed          59             71             65   
998               completed          68             78             77   
999                    none          77             86             86   

        education_cat  
0    высшая категория  
1              низшая  
2    высшая категория  
3    высшая категория  
4              низшая  
..                ...  
995  высшая категория  
996     выше среднего  
997     выше среднего  
998            низшая  
999            низшая  

[1000 rows x 9 columns]

# Практическая работа №8

## Задание
У какого из режиссеров самый высокий процент фильмов со сборами выше 
бюджета?

In [274]:
import pandas as pd
import numpy as np

def luck_film(budget, revenue):
    c = revenue - budget
    if c>0:
        return True
    else:
        return False

def percent_luck(row):
    if row[1] == 0:
        return row[0]/1*100
    else:
        return row[0]/(row[0]+row[1])*100
    
def analog_luck(row):
    return row[0]/(row[0]+row[1])*100
df = pd.read_csv('../films.csv')

In [275]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   imdb_id               1890 non-null   object 
 1   popularity            1890 non-null   float64
 2   budget                1890 non-null   int64  
 3   revenue               1890 non-null   int64  
 4   original_title        1890 non-null   object 
 5   cast                  1890 non-null   object 
 6   director              1890 non-null   object 
 7   tagline               1890 non-null   object 
 8   overview              1890 non-null   object 
 9   runtime               1890 non-null   int64  
 10  genres                1890 non-null   object 
 11  production_companies  1890 non-null   object 
 12  release_date          1890 non-null   object 
 13  vote_count            1890 non-null   int64  
 14  vote_average          1890 non-null   float64
 15  release_year         

In [276]:
df.loc[:,'luck'] = list(map(luck_film, df['budget'], df['revenue']))



df1 = df.groupby('luck').get_group(True)
df2 = df.groupby('luck').get_group(False)
df1 = df1.groupby('director').agg({'luck':'value_counts'})
df2 = df2.groupby('director').agg({'luck':'value_counts'})
df1 = df1.reset_index(level='luck',drop=True)
df2 = df2.reset_index(level='luck',drop=True)


df1.columns=['value_luck']
df2.columns=['value_unluck']

df2


value_unluck
director                         
Adam Shankman                   1
Adam Wingard                    1
Akiva Goldsman                  1
Alan Parker                     1
Alejandro Amenábar             1
...                           ...
William Dear                    1
William Friedkin                2
William Malone                  1
William Monahan                 1
Zal Batmanglij                  1

[354 rows x 1 columns]

In [278]:
df3 = pd.concat([df1, df2], ignore_index=False)
df3['director'] = df3.index
df3 = df3.reset_index(level='director',drop=True)
df3 = df3.fillna(0)
listing = map(lambda x: percent_luck(list(df3.iloc[x])), range(len(df3['director'])))
df3['listing'] = list(listing)
m = max(df3['listing'])
df3.loc[df3['listing']==m]

value_luck  value_unluck      director  listing
596        12.0           0.0  Ridley Scott   1200.0

In [270]:
df3

value_luck  value_unluck                       director  listing
0            1.0           0.0  Aaron Seltzer|Jason Friedberg    100.0
1            6.0           0.0                     Adam McKay    600.0
2            7.0           0.0                  Adam Shankman    700.0
3            1.0           0.0                    Adrian Lyne    100.0
4            1.0           0.0                      Alan Poul    100.0
...          ...           ...                            ...      ...
1123         0.0           1.0                   William Dear      0.0
1124         0.0           2.0               William Friedkin      0.0
1125         0.0           1.0                 William Malone      0.0
1126         0.0           1.0                William Monahan      0.0
1127         0.0           1.0                 Zal Batmanglij      0.0

[1128 rows x 4 columns]