# Практическая работа № 5

In [4]:
import numpy as np #Библиотека NumPy. Импорт библиотеки
#Создание массива. Функции array() и values().

F = np.random.randint(50,55,(5,4))
print(F)

[[52 53 52 54]
 [52 51 53 51]
 [51 54 50 50]
 [52 52 50 51]
 [54 51 53 54]]


In [4]:
k=0
var_my=0
for i in range(len(F)):
    for g in range(len(F[i])):
        var_my += (np.mean(F) - F[i][g])**2
        if F[i][g] == np.min(F):
            k+=1
            print(i+1,g+1)
print(k,'Кол-во значений соответствующих минимуму')
std_my = np.sqrt(var_my/(len(F)*len(F[1])))
print(round(std_my,2),'Стандартное отклонение матрицы, по формулам')
print(round(np.std(F),2),'Стандартное отклонение матрицы, стандартная функция')

1 4
2 3
3 2
3 4
4 2
4 3
5 2
5 3
8 Кол-во значений соответствующих минимуму
0.49 Стандартное отклонение матрицы, по формулам
0.49 Стандартное отклонение матрицы, стандартная функция


In [42]:
len(F)

5

In [61]:
round(2.55,1)

2.5